config/routes.rb
Rails.application.routes.draw do
  resources :videos
  resources :series
  resources :genres
  devise_for :users
   resource :contents, :only => :new

      post 'get_videos' => 'series#get_videos'
      post 'get_movie' => 'videos#get_movie'
      post 'set_time' => 'videos#set_time'
      post 'manage_genre' => 'videos#manage_genre'
      get 'movies' => 'videos#movies'
      get 'search' => 'videos#search'

end

app/models/genre.rb
class Genre < ActiveRecord::Base
  has_and_belongs_to_many :series
  has_and_belongs_to_many :videos
  belongs_to :user


  def nameortype
    name
  end
end

app/controllers/genres_controller.rb
class GenresController < ApplicationController
  before_action :set_genre, only: [:show, :edit, :update, :destroy]

  # GET /genres
  # GET /genres.json
  def index
    @genres = current_user.genres.all
    if params[:genre] && params[:type]
      @genre= params[:genre]
      @type= params[:type]
      @genre=Genre.where("name LIKE ?",@genre).last
      if @type == "series"
        @videos=@genre.series
      else
        @videos=@genre.videos.where("production_type LIKE ?",@type)
      end
    end

  end

  # GET /genres/1
  # GET /genres/1.json
  def show
  end

  # GET /genres/new
  def new
    @genres = current_user.genres.all
    @genre = current_user.genres.build
  end

  # GET /genres/1/edit
  def edit
  end

  # POST /genres
  # POST /genres.json
  def create
    @genre = current_user.genres.build(genre_params)

    respond_to do |format|
      if @genre.save
        format.html { redirect_to "/genres", notice: 'Genre was successfully created.' }
        format.json { render :show, status: :created, location: @genre }
      else
        format.html { render :new }
        format.json { render json: @genre.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /genres/1
  # PATCH/PUT /genres/1.json
  def update
    respond_to do |format|
      if @genre.update(genre_params)
        format.html { redirect_to @genre, notice: 'Genre was successfully updated.' }
        format.json { render :show, status: :ok, location: @genre }
      else
        format.html { render :edit }
        format.json { render json: @genre.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /genres/1
  # DELETE /genres/1.json
  def destroy
    @genre.destroy
    respond_to do |format|
      format.html { redirect_to "/genres/new", notice: 'Genre was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_genre
      @genre = Genre.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def genre_params
      params.require(:genre).permit(:name, series_ids:[] ,video_ids:[])
    end
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/views/genres/_form.html.erb
<%= form_for(@genre) do |f| %>
  <% if @genre.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@genre.errors.count, "error") %> prohibited this genre from being saved:</h2>

      <ul>
      <% @genre.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <% f.label :series %><br>
    <% f.collection_check_boxes(:series_ids, Series.all, :id, :title) %>
  </div>
  <div class="field">
    <% f.label :videos, "Movies" %><br>
    <% f.collection_check_boxes(:video_ids, Video.where("production_type LIKE ?",'movie'), :id, :title) %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>


<% end %>


<div class='delete_genres'>
<h1>Delete Genres</h1>
  <% @genres.each do |genre| %>
  <div class="">
    <%= truncate(genre.name,:length => 15) %>
    <%= link_to 'Delete', genre, method: :delete, data: { confirm: 'Are you sure?' } %>
  </div>
  <%end%>
</div>

app/views/genres/edit.html.erb
<h1>Editing Genre</h1>

<%= render 'form' %>

<%= link_to 'Show', @genre %> |
<%= link_to 'Back', genres_path %>

app/views/genres/index.html.erb
<h1>Listing Genres</h1>


<div id='form_wrapper'>
  <form id='genres'>
    <div class="container">
      <h2>Genre</h2>
      <ul class="list">
        <% @genres.each do |genre| %>
        <li class="list__item">
          <%= radio_button_tag 'genre', "#{genre.name}", @genre && @genre.name == genre.name ? true : false,class:"radio-btn"%>
          <%=label_tag 'genre_'+genre.name, truncate(genre.name,:length => 10),class:"label"%>
          <% genre.name %>
          <% link_to 'Show', genre %>
          <% link_to 'Edit', edit_genre_path(genre) %>
          <% link_to 'Destroy', genre, method: :delete, data: { confirm: 'Are you sure?' } %>
        </li>
        <%end%>
      </ul>
    </div>
  </form>

<div id='line'></div>
  <form id='types'>
    <div class="container">
      <h2>Type</h2>
      <ul class="list">
        <%= radio_button_tag 'type', "movie", @type == "movie" ? true : false,class:"radio-btn" %>
        <%=label_tag 'type_'+"movie", "movie",class:"label"%>

        <%= radio_button_tag 'type', "series", @type == "series" ? true : false,class:"radio-btn" %>
        <%=label_tag 'type_'+"series", "series",class:"label"%>

        <%= radio_button_tag 'type', "other", @type == "other" ? true : false,class:"radio-btn" %>
        <%=label_tag 'type_'+"other", "other",class:"label"%>
      </ul>
    </div>
  </form>
</div>
<%= link_to 'Mange Genres', new_genre_path,class:"mange_genres" %>



<% if @type == "series"%>
<h1>Listing Series</h1>
<div id='series_wrapper'>
  <%@counter=1%>
  <% if @videos.count == 0 %>
      <h1>No Videos matching your request</h1>
  <%else%>
    <% @videos.each do |series| %>
      <%@search = Tmdb::Search.new %>
      <%@search.resource('tv') %>
      <%@search.query(series.title) %>
      <%@tv_series_id=@search.fetch[0]["id"] %>
      <%@pics = Tmdb::TV.images(@tv_series_id) %>
      <% @pics['backdrops'][1]["file_path"] %>
      <%= image_tag("http://image.tmdb.org/t/p/w780/#{@pics['backdrops'][1]["file_path"]}", :class => "#{series.title}", :id=>@counter)%>
      <%@counter+=1%>
    <% end %>
  <%end%>
</div>


  <script>
  function hasClass(elem, className) {
      return elem.className.split(' ').indexOf(className) > -1;
  }



  $("img").click(function(){
    $("#dropdown").remove();
    if ($(this).attr("id")%2 == 0) {
      $(this).after("<div id='dropdown'><h1>"+$(this).attr('class')+"</h1></div>");
    } else if ( $(this).next().length == 0) {
      $(this).after("<div id='dropdown'><h1>"+$(this).attr('class')+"</h1></div>");
    } else {
      $(this).next().after("<div id='dropdown'><h1>"+$(this).attr('class')+"</h1></div>");
    }

    var classs=$(this).attr('class')
    $.ajax({
      type: "POST",
      url: "/get_videos",
      dataType:"json",
      data: {"title":$(this).attr('class')},
      success:function(data) {
        var total_seasons=data["total_seasons"];
        var season=data["season"];
        var series=data["series"]
        var videos=data["videos"]
        var amount=videos.length
        $( " <a href='/series/"+data["id"]+"/edit'>Edit</a> " ).appendTo( "#dropdown" );
        $( "<h2>"+data["series"]["desc"]+"</h2>" ).appendTo( "#dropdown" );
        $("<h4>"+amount+" episodes<br>Season: </h4>").appendTo( "#dropdown" );
        var s = $("<select id='season_select' class='"+classs+" seaon_select' />");
        s.appendTo('#dropdown');


        $( "<div class='owl-carousel'></div>" ).appendTo( "#dropdown" );
        for(i=0;i<amount;i++){
          if (videos[i]["desc"].length>300) {
            var desc= videos[i]["desc"].substring(0, 300)+"...";
          } else {
            var desc= videos[i]["desc"];
          };
          if (videos[i]["total_time"] != null) {
            var remaining=(videos[i]["left_off"]/videos[i]["total_time"])*100
          } else {
            var remaining=0
          }
          // VIDEO DIV
          $("<div class='video_divs'><a href='/videos/"+videos[i]["id"]+"'> <img src="+videos[i]["poster"]+
          "  /> </a> <p class='video_title'>"+videos[i]["title"]+
          "</p><p><div class='meter'><span style='width: "+remaining+"%'></span></div></p>  <p class='video_desc'>"+desc+"</h3></div>").appendTo( ".owl-carousel" );


        }
        $(".owl-carousel").owlCarousel({
          items : 5,
          margin: 20,
          responsiveClass:true,
          responsive:{
              0:{
                  items:1
              },
              600:{
                  items:3
              },
              1000:{
                  items:5
              }
          }
        });
        $("p:contains("+data["last_watched"]+")").parent().css({"color":"black","background-color":"#F2E980"})
        for(var val in total_seasons) {
            $('<option />', {value: total_seasons[val], text: total_seasons[val]}).appendTo(s);
        }
        $("#season_select").val(season);
      },
      error:function(data) {
        $( " <a href='/series/"+data['responseJSON']['id']+"/edit'>Edit</a> " ).appendTo( "#dropdown" );
        $( "<h2>No Episodes Added Yet <br>  <a href='/videos/new'>Add Some Now!</a> </h2>" ).appendTo( "#dropdown" );
        return false;
      }
    });
  });

  document.addEventListener('change', function (e) {
      if (hasClass(e.target, 'seaon_select')) {
                var name = $('#season_select').attr('class').slice(0, -13)
                var season_number=$( "#season_select option:selected" ).text()
              //alert($(this).val());
              // RESENDS AJAX REQUEST WHEN CHANGING SEASON NUMBER*****************************
                $(".owl-carousel").remove();
                $('h2').remove();
                $('h4').remove();
                $('#season_select').remove();
                $( "#dropdown a" ).remove();
                var classs=name;
                $.ajax({
                  type: "POST",
                  url: "/get_videos",
                  dataType:"json",
                  data: {"title":name,"season":season_number},
                  success:function(data) {
                    var total_seasons=data["total_seasons"];
                    var season=data["season"];
                    var series=data["series"];
                    var videos=data["videos"];
                    var amount=videos.length;
                    $( " <a href='/series/"+data["id"]+"/edit'>Edit</a> " ).appendTo( "#dropdown" );
                    $( "<h2>"+data["series"]["desc"]+"</h2>" ).appendTo( "#dropdown" );
                    $("<h4>"+amount+" episodes<br>Season: </h4>").appendTo( "#dropdown" );
                    var s = $("<select id='season_select' class='"+classs+" seaon_select' />");
                    s.appendTo('#dropdown');
                    $( "<div class='owl-carousel'></div>" ).appendTo( "#dropdown" );
                    for(i=0;i<amount;i++){
                      if (videos[i]["desc"].length>300) {
                        var desc= videos[i]["desc"].substring(0, 300)+"...";
                      } else {
                        var desc= videos[i]["desc"];
                      };
                      if (videos[i]["total_time"] != null) {
                        var remaining=(videos[i]["left_off"]/videos[i]["total_time"])*100
                      } else {
                        var remaining=0
                      }
                      // VIDEO DIV
                      $("<div class='video_divs'><a href='/videos/"+videos[i]["id"]+"'> <img src="+videos[i]["poster"]+
                      "  /> </a> <p class='video_title'>"+videos[i]["title"]+
                      "</p><p><div class='meter'><span style='width: "+remaining+"%'></span></div></p>  <p class='video_desc'>"+desc+"</h3></div>").appendTo( ".owl-carousel" );

                    }
                    $(".owl-carousel").owlCarousel({
                      items : 5,
                      margin: 20,
                      responsiveClass:true,
                      responsive:{
                          0:{
                              items:1
                          },
                          600:{
                              items:3
                          },
                          1000:{
                              items:5
                          }
                      }
                    });
                    $("p:contains("+data["last_watched"]+")").parent().css({"color":"black","background-color":"#F2E980"})
                    for(var val in total_seasons) {
                        $('<option />', {value: total_seasons[val], text: total_seasons[val]}).appendTo(s);
                    }
                    $("#season_select").val(season);
                  },
                  error:function(data) {
                    $( " <a href='/series/"+data['responseJSON']['id']+"/edit'>Edit</a> " ).appendTo( "#dropdown" );
                    $( "<h2>No Episodes Added Yet <br>  <a href='/videos/new'>Add Some Now!</a> </h2>" ).appendTo( "#dropdown" );
                    return false;
                  }
                });
      }
  }, false);

  </script>





<%elsif @type == "movie" %>
  <h1>Listing Movies</h1>
  <%@counter=1%>
  <div id='movies_index_wrapper'>
    <% if @videos.count == 0 %>
        <h1>No Videos matching your request</h1>
    <%else%>
        <% @videos.each do |video| %>
            <% if @counter == 1%>
              <div>
            <%end%>
            <%= image_tag(video.poster, :class => "#{video.title}", :id=>@counter)%>
            <%@counter+=1%>
            <% if @counter == 5 %>
              </div>
              <%@counter=1%>
            <%end%>
        <% end %>
      <%end%>
  </div>



  <script>




  $("img").click(function(){
    $("#dropdown").remove();


      $(this).parent().after("<div id='dropdown'><h1>"+$(this).attr('class')+"</h1></div>");


    var classs=$(this).attr('class')
    $.ajax({
      type: "POST",
      url: "/get_movie",
      dataType:"json",
      data: {"title":$(this).attr('class')},
      success:function(data) {
        console.log(data);


  //        if (videos[i]["desc"].length>300) {
  //          var desc= videos[i]["desc"].substring(0, 300)+"...";
  //        } else {
  //          var desc= videos[i]["desc"];
  //        };
  //        if (videos[i]["total_time"] != null) {
  //          var remaining=(videos[i]["left_off"]/videos[i]["total_time"])*100
  //        } else {
  //          var remaining=0
  //        }
          // VIDEO DIV
          $("<div class='movie_preview_div'><a href='/videos/"+data["id"]+"'> <img src='"+data["img"]+
         "'></a><p><div class='meter'><span style='width: "+data["remaining"]+"%'></span></div></p>  <p class='movie_desc'>"+data["desc"]+"</h3></div>").appendTo( "#dropdown" );


      },
      error:function(data) {
        console.log("bad");
        console.log(data);
        alert("Error Occurred! Please make sure there is a user using the Email entered.")
        return false;
      }
    });


  })

    </script>


<%end%>


<script>

if ($("#genres input[type='radio']:checked").val() == undefined) {
    console.log("BAD");
    $('#genres input[type=radio]:first').attr('checked', true);
}

if ($("#types input[type='radio']:checked").val() == undefined) {
    console.log("BAD");
    $('#types input[type=radio]:first').attr('checked', true);
}

$(function(){
  $('input[type="radio"]').click(function(){
    if ($(this).is(':checked'))
    {
      var type= $("#types input[type='radio']:checked").val();
      var genre= $("#genres input[type='radio']:checked").val();
      $(location).attr('href',"/genres?genre="+genre+"&type="+type+"");
    }
  });
});

</script>

app/views/genres/new.html.erb
<h1>New Genre</h1>

<%= render 'form' %>

app/views/genres/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @genre.name %>
</p>

<%= link_to 'Edit', edit_genre_path(@genre) %> |
<%= link_to 'Back', genres_path %>