config/routes.rb
Rails.application.routes.draw do
  resources :videos
  resources :series
  resources :genres
  devise_for :users
   resource :contents, :only => :new

      post 'get_videos' => 'series#get_videos'
      post 'get_movie' => 'videos#get_movie'
      post 'set_time' => 'videos#set_time'
      post 'manage_genre' => 'videos#manage_genre'
      get 'movies' => 'videos#movies'
      get 'search' => 'videos#search'

end

app/models/video.rb
class Video < ActiveRecord::Base

   has_and_belongs_to_many :genres
   belongs_to :series
   belongs_to :user
   validate :check_title
   validate :content_type
   validate :series_check
   validate :season_episode
   after_validation  :add_title_and_desc
   #validate :add_title_and_desc, :on => :create
   mount_uploader :content, ContentUploader
  #  has_attached_file :content, default_url: "/images/:style/missing.png"
   # validates_attachment_content_type :content, content_type: /\Avideo\/.*\z/
   # validates :content, attachment_presence: true

   before_destroy :delete_content

  private
  def set_success(format, opts)
    self.success = true
  end

  def delete_content
    self.remove_content!
  end

  def content_type
    if self.content.file.extension.downcase.in?(["mp4","webm","ogg"]) == false
      errors.add(:content_type, "has to be either mp4, webm or ogg")
    end
  end
  def check_title
    if self.production_type.downcase == "movie" && self.title.length < 1
        errors.add(:Movies,' must have a title')
    end
  end
  def series_check
    if self.production_type !=nil && self.production_type.downcase == "tv"
      if self.series == nil
        errors.add(:video, "must belong to a series")
      end
    end
  end

  def season_episode
    if self.production_type !=nil && self.production_type.downcase == "tv"
      if self.season == nil || self.episode == nil
        errors.add(:video, "must have a season and episode number")
      end
    end
  end

  def add_title_and_desc
    return unless errors.blank?
    @search = Tmdb::Search.new
    if self.production_type==nil
      errors.add(:type, "must have a tv, movie or other type")
    else
      if self.production_type.downcase == "tv"
        @search.resource('tv')
        if self.series
          @search.query(self.series.title)
          if @search.fetch.any?
            @tv_series_id=@search.fetch[0]["id"]
            @episode = Tmdb::Episode.detail(@search.fetch[0]["id"] , self.season, self.episode)
            @episode_title= @episode["name"]
            @episode_desc= @episode["overview"]
            @episode_date= @episode["air_date"]
            if self.season != nil || self.episode != nil
              @pics = Tmdb::Episode.images(@tv_series_id, self.season, self.episode)
              if @pics["stills"] != nil
                if @pics["stills"][1]==nil
                  @poster= "http://image.tmdb.org/t/p/w780/#{ @pics["stills"][0]["file_path"]}"
                else
                  @poster= "http://image.tmdb.org/t/p/w780/#{ @pics["stills"][1]["file_path"]}"
                end
                self.date = @episode_date.to_date
                self.poster = @poster
              else
                @poster= "/tv_placeholder.jpg"
                self.poster = @poster
              end

              if self.title==""||self.title==nil
                self.title = @episode_title
              end
              if self.desc=="" || self.desc==nil
                self.desc = @episode_desc
              end
              if self.title==""|| self.title==nil
                self.title = "N/A"
              end
              if self.desc=="" || self.desc==nil
                self.desc = "N/A"
              end

            end
          end
        end
      elsif self.production_type.downcase=="movie"
        @search = Tmdb::Search.new
        @search.resource('movie')
        @search.query(self.title)
        if @search.fetch[0] != nil
          @movie_id=@search.fetch[0]["id"]
          @movie = Tmdb::Movie.detail(@movie_id)
          @movie_desc=@movie["overview"]
          @movie_date=@movie["release_date"]
          @poster= "http://image.tmdb.org/t/p/w780/#{ @movie["poster_path"]}"
          @movie_img="http://image.tmdb.org/t/p/w780/#{ @movie["backdrop_path"]}"
          self.poster=@poster
          self.movie_img=@movie_img
          self.desc=@movie_desc
          self.date=@movie_date.to_date
        else
          @poster= "/placeholder.jpg"
          @movie_img="/tv_placeholder.jpg"
          self.poster=@poster
          self.movie_img=@movie_img
        end
      end
    end
  end



end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  before_action :set_video, only: [:show, :edit, :update, :destroy]


  def search
    @search=params[:search]
    if params[:type]==nil || params[:type]=='movie'
      @type='movie'
      @videos=Video.where("title LIKE ? AND production_type LIKE ?","%#{@search}%","movie")
    else
      @type='series'
      @videos=Series.where("title LIKE ?","%#{@search}%")
    end
  end

  def manage_genre
    @genre=Genre.where("name LIKE ?",params[:genre].humanize.downcase)
    @genre=@genre.last
    if params[:movie]=="true"
      @video=Video.find(params[:id])
    else
      @video=Series.find(params[:id])
    end

    if @video.genres.include? @genre
      @video.genres.delete(@genre)
      respond_to do |format|
        format.json { render :json => {:report =>"remove" } }
      end
    else
      @video.genres<<@genre
      respond_to do |format|
        format.json { render :json => {:report =>"add" } }
      end
    end

  end

  def movies
    @videos=Video.where("production_type LIKE ?",'movie')
  end

  def get_movie
    @movie=Video.where("title LIKE ?",params[:title])
    @movie=@movie.last
    @desc=@movie.desc[0..300].gsub(/\s\w+\s*$/, '...')
            if @movie.total_time.nil?
               @remaining=0
            else
               @remaining=(@movie.left_off.to_f/@movie.total_time.to_f)*100
            end
    respond_to do |format|
      format.json { render :json => {:desc =>@desc , :img => @movie.movie_img, id:@movie.id, remaining:@remaining} }
    end
  end

  def set_time
    if params[:time] && params[:video] && params[:total]
      @time=params[:time]
      @video=Video.find(params[:video])
      @video.left_off=@time
      @video.last_watched= Time.now
      @video.total_time=params[:total]
      @video.save
      respond_to do |format|
        format.json { render :json => {:time => @time} }
      end

    else

    end

  end
  # GET /videos
  # GET /videos.json
  def index
    Video.delete_all("title IS NULL")
    @videos = Video.all
  end

  # GET /videos/1
  # GET /videos/1.json
  def show
    if @video.production_type.downcase=="tv"
       @search = Tmdb::Search.new
       @search.resource('tv')
       @search.query(@video.series.title)
       @tv_series_id=@search.fetch[0]["id"]
       @episode = Tmdb::Episode.detail(@search.fetch[0]["id"] , @video.season, @video.episode)
       @episode_title= @episode["name"]
       @episode_desc= @episode["overview"]
       @episode_date= @episode["air_date"]
       @genres=[]
       @video.series.genres.each do |g|
         @genres.push(g.name.parameterize.underscore)
       end
       @pics = Tmdb::Episode.images(@tv_series_id, @video.season, @video.episode)
       if @pics["stills"] != nil
         if @pics["stills"][1]==nil
           @poster= "http://image.tmdb.org/t/p/w780/#{ @pics["stills"][0]["file_path"]}"
         else
           @poster= "http://image.tmdb.org/t/p/w780/#{ @pics["stills"][1]["file_path"]}"
         end
       end


       @season_eps= @video.series.videos.where("season LIKE #{@video.season} AND episode > #{@video.episode}").all

       if @season_eps.count > 0
         @season_eps=@season_eps.sort_by &:episode
         @next_eps=@season_eps.first
         gon.next_eps="/videos/#{@next_eps.id}"
       elsif  @video.series.videos.where("season > #{@video.season}").all.count > 0
         @season_eps= @video.series.videos.where("season > #{@video.season}").all
         @season_eps=@season_eps.sort_by {|x| [x.season, x.episode] }
         @next_eps=@season_eps.first
         gon.next_eps="/videos/#{@next_eps.id}"
       else
         gon.next_eps="end"
       end
       gon.genre_id = @video.series.id
       gon.movie=false

     elsif @video.production_type.downcase == "movie"
       @search = Tmdb::Search.new
       @search.resource('movie')
       @search.query(@video.title)
       if @search.fetch[0] != nil
         @movie_id=@search.fetch[0]["id"]
         @movie = Tmdb::Movie.detail(@movie_id)
         @movie_desc=@movie["overview"]
         @movie_date=@movie["release_date"]
         @poster= "http://image.tmdb.org/t/p/w780/#{ @movie["backdrop_path"]}"
       else
          @poster= "/placeholder.jpg"
       end
       gon.genre_id = @video.id
       gon.movie=true
       @genres=[]
       @video.genres.each do |g|
         @genres.push(g.name.parameterize.underscore)
       end
     end

     gon.genres=@genres
     gon.id = @video.id
     if @video.left_off != nil
       gon.start=0.00+@video.left_off
     else
       gon.start=0.00
     end

  end

  # GET /videos/new
  def new
    @video = current_user.videos.build
    @video.update_attribute :key, params[:key] # different than documentation!!
  end

  # GET /videos/1/edit
  def edit
  end

  # POST /videos
  # POST /videos.json
  def create
    @video = current_user.videos.build(video_params)
    respond_to do |format|
      if @video.save
        format.html { redirect_to @video, notice: 'Video was successfully created.' }
        format.json { render :show, status: :created, location: @video }
      else
        format.html { render :new }
        format.json { render json: @video.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /videos/1
  # PATCH/PUT /videos/1.json
  def update
    respond_to do |format|
      if @video.update(video_params)
        format.html { redirect_to @video, notice: 'Video was successfully updated.' }
        format.json { render :show, status: :ok, location: @video }
      else
        format.html { render :edit }
        format.json { render json: @video.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /videos/1
  # DELETE /videos/1.json
  def destroy
    @video.destroy
    respond_to do |format|
      format.html { redirect_to "/", notice: 'Video was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_video
      @video = Video.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def video_params
      params.require(:video).permit(:content,:production_type, :title, :season, :episode, :desc, :date, :series_id, genre_ids:[])
    end
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/videos/_form.html.erb
<%= form_for(@video)do |f| %>
  <% if @video.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@video.errors.count, "error") %> prohibited this video from being saved:</h2>

      <ul>
      <% @video.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
      <%= f.radio_button(:production_type, "Movie") %>
      <%= f.label(:production_type_movie, "Movie") %>
      <%= f.radio_button(:production_type, "TV",class:'tv_type') %>
      <%= f.label(:production_type_tv, "TV") %>
      <%= f.radio_button(:production_type, "Other") %>
      <%= f.label(:production_type_other, "Other") %>
  </div>
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field series">
    <%= f.label :series_id %><br>
    <%= f.collection_radio_buttons(:series_id, Series.all, :id, :title) %>
  </div>
  <div class="field">
    <%= f.label :season %><br>
    <%= f.number_field :season %>
  </div>
  <div class="field">
    <%= f.label :episode %><br>
    <%= f.number_field :episode %>
  </div>
  <div class="field">
    <%= f.label :desc ,"Description" %><br>
    <%= f.text_area :desc %>
  </div>


  <%= f.hidden_field :key %>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>



<script>
if ($('.tv_type').is(':checked')){
  $(".series input").prop("disabled",false);
  $("input[type=number]").prop("disabled",false);
}
if ($('.tv_type').is(':not(:checked)')){
  $(".series input").prop("disabled",true);
  $("input[type=number]").prop("disabled",true);
  $("#video_title").prop("disabled",false);
}
  $(function(){
    $('input[type=radio]').click(function(){
      if ($('.tv_type').is(':checked')){
        $(".series input").prop("disabled",false);
        $("input[type=number]").prop("disabled",false);
      }
      if ($('.tv_type').is(':not(:checked)')){
        $(".series input").prop("disabled",true);
        $("input[type=number]").prop("disabled",true);
        $("#video_title").prop("disabled",false);
      }
    });
  });

</script>

app/views/videos/_newform.html.erb
<%= form_for(@video)do |f| %>
  <% if @video.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@video.errors.count, "error") %> prohibited this video from being saved:</h2>

      <ul>
      <% @video.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <%= link_to new_contents_path do %>
     Upload  <%=image_tag 'upload.png'%>
<% end %>
  <div class="field">
      <%= f.radio_button(:production_type, "Movie") %>
      <%= f.label(:production_type_movie, "Movie") %>
      <%= f.radio_button(:production_type, "TV",class:'tv_type') %>
      <%= f.label(:production_type_tv, "TV") %>
      <%= f.radio_button(:production_type, "Other") %>
      <%= f.label(:production_type_other, "Other") %>
  </div>
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field series">
    <%= f.label :series_id %><br>
    <%= f.collection_radio_buttons(:series_id, Series.all, :id, :title) %>
  </div>
  <div class="field">
    <%= f.label :season %><br>
    <%= f.number_field :season, disabled: true %>
  </div>
  <div class="field">
    <%= f.label :episode %><br>
    <%= f.number_field :episode, disabled: true %>
  </div>
  <%= hidden_field_tag :desc%>

  <%= f.hidden_field :key %>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>


<script>
function getParameterByName( name ){
  name = name.replace(/[\[]/,"\\\[").replace(/[\]]/,"\\\]");
  var regexS = "[\\?&]"+name+"=([^&#]*)";
  var regex = new RegExp( regexS );
  var results = regex.exec( window.location.href );
  if( results == null )
    return "";
  else
    return decodeURIComponent(results[1].replace(/\+/g, " "));
}

  $(".field").hide();
  $("input[type=submit]").hide();

  $(".series input").prop("disabled",true);

  if (getParameterByName('bucket') != '') {
    $(".field").show();
    $("input[type=submit]").show();
  }

  $(function(){
    $('input[type=radio]').click(function(){
      if ($('.tv_type').is(':checked')){
        $(".series input").prop("disabled",false);
        $("input[type=number]").prop("disabled",false);
        $("#video_title").prop("disabled",true);
      }
      if ($('.tv_type').is(':not(:checked)')){
        $(".series input").prop("disabled",true);
        $("input[type=number]").prop("disabled",true);
        $("#video_title").prop("disabled",false);
      }
    });
  });

</script>

app/views/videos/edit.html.erb
<h1>Editing Video</h1>
<p class='edit_p'>(Fill in title and or description boxs to put in custom information else leave blank so that info will be replaced by the Movie DB according to title or season and episode numbers)</p>
<%= render 'form' %>
<%= link_to 'Delete Video', @video, method: :delete, data: { confirm: 'Are you sure?' },class: 'delete_link' %>

app/views/videos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Videos</h1>
<%= link_to 'New Video', new_video_path %>

<table>
  <thead>
    <tr>
      <th>Type</th>
      <th>Title</th>
      <th>Season</th>
      <th>Episode</th>
      <th>Desc</th>
      <th>Time Left Off</th>
      <th>Total Length</th>
      <th>Last Watched</th>
      <th>Date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @videos.each do |video| %>
      <tr>
        <td><%= video.production_type %></td>
        <td><%= video.title %></td>
        <td><%= video.season %></td>
        <td><%= video.episode %></td>
        <td><%= video.desc %></td>
        <td><%= video.left_off %></td>
        <td><%= video.total_time %></td>
        <td><%= video.last_watched %></td>
        <td><%= video.date %></td>
        <td><%= link_to 'Show', video %></td>
        <td><%= link_to 'Edit', edit_video_path(video) %></td>
        <td><%= link_to 'Destroy', video, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Video', new_video_path %>

app/views/videos/movies.html.erb
<%@counter=1%>
<div id='movies_index_wrapper'>
  <h1>Listing Movies</h1>
<h2><%= link_to 'Add New Movie', new_video_path,:class => 'video_link' %></h2>
    <% @videos.each do |video| %>
        <% if @counter == 1%>
          <div>
        <%end%>
        <%= image_tag(video.poster, :class => "#{video.title}", :id=>@counter)%>
        <%@counter+=1%>
        <% if @counter == 5 %>
          </div>
          <%@counter=1%>
        <%end%>
    <% end %>

</div>

<h1>Thats all your movies!</h1>
<h2 style="text-align:center;"><%= link_to 'Add More', new_video_path,:class => 'video_link'%></h2>

<script>




$("img").click(function(){
  $("#dropdown").remove();


    $(this).parent().after("<div id='dropdown'><h1>"+$(this).attr('class')+"</h1></div>");


  var classs=$(this).attr('class')
  $.ajax({
    type: "POST",
    url: "/get_movie",
    dataType:"json",
    data: {"title":$(this).attr('class')},
    success:function(data) {
      console.log(data);


//        if (videos[i]["desc"].length>300) {
//          var desc= videos[i]["desc"].substring(0, 300)+"...";
//        } else {
//          var desc= videos[i]["desc"];
//        };
//        if (videos[i]["total_time"] != null) {
//          var remaining=(videos[i]["left_off"]/videos[i]["total_time"])*100
//        } else {
//          var remaining=0
//        }
        // VIDEO DIV
        $("<div class='movie_preview_div'><a href='/videos/"+data["id"]+"'> <img src='"+data["img"]+
       "'></a><p><div class='meter'><span style='width: "+data["remaining"]+"%'></span></div></p>  <p class='movie_desc'>"+data["desc"]+"</h3></div>").appendTo( "#dropdown" );


    },
    error:function(data) {
      console.log("bad");
      console.log(data);
      alert("Error Occurred! Please make sure there is a user using the Email entered.")
      return false;
    }
  });


})

  </script>

app/views/videos/new.html.erb
<h1>Add New Video</h1>

<%= render 'newform' %>

app/views/videos/show.html.erb
<% if @video.production_type.downcase == 'tv'%>
<div id='video_show_wrapper'>
  <div id="video_container">
     <video id="player" width="400" controls autoplay poster=<%=@video.poster%>>
       <source src=<%=@video.content.url%> type="video/mp4">
       <source src=<%=@video.content.url%> type="video/ogg">
       Your browser does not support HTML5 video.
     </video>
  </div>
  <h1>Video Information</h1>
  <table>
  <tr>
    <th>Title</th>
    <td><%= @video.title %></td>
  </tr>
  <tr>
    <th>Season</th>
    <td><%= @video.season%></td>
  </tr>
  <tr>
    <th>Episode</th>
    <td><%= @video.episode%></td>
  </tr>
  <tr>
    <th>Air Date</th>
    <td><%= @video.date%></td>
  </tr>
  <tr>
    <th>Series</th>
    <td><%= @video.series.title%></td>
  </tr>
  <tr>
    <th>Last Watched</th>
    <td><%= @video.last_watched%></td>
  </tr>
</table>
<h2>Description</h2>
  <p><%= @video.desc %></p>

  <div class='genre_form'>
    <select>
      <option disabled selected value> -- select an option -- </option>
      <% current_user.genres.all.each do |g| %>
        <option value=<%=g.name.parameterize.underscore.downcase%>><%=g.name%></option>
      <%end%>
    </select>
    <button class="button button1">Add/Remove Genre</button>
  </div>

  <p>
    <strong>Genres:</strong><br>
    <% @video.series.genres.each do |g| %>
      <%=g.name%><br>
    <%end%>
  </p>


<%elsif @video.production_type.downcase == 'movie'%>
<div id='video_show_wrapper'>
  <div id="video_container">
     <video id="player" width="400" controls autoplay poster=<%=@video.movie_img%>>
       <source src=<%=@video.content.url%> type="video/mp4">
       <source src=<%=@video.content.url%> type="video/ogg">
       Your browser does not support HTML5 video.
     </video>
  </div>

  <h1>Video Information</h1>

  <table>
  <tr>
    <th>Title</th>
    <td><%= @video.title %></td>
  </tr>
  <tr>
    <th>Release Date</th>
    <td><%= @video.date%></td>
  </tr>
  <tr>
    <th>Last Watched</th>
    <td><%= @video.last_watched%></td>
  </tr>
</table>
<h2>Description</h2>
<p><%= @video.desc %></p>

<div class='genre_form'>
  <div class="select-style">
    <select>
      <option disabled selected value> -- select an option -- </option>
      <% current_user.genres.all.each do |g| %>
        <option value=<%=g.name.parameterize.underscore.downcase%>><%=g.name%></option>
      <%end%>
    </select>
  </div>
  <button class="button button1">Add/Remove Genre</button>
</div>

<p>
  <strong>Genres:</strong><br>
  <% @video.genres.each do |g| %>
    <%=g.name%><br>
  <%end%>
</p>
<%end%>






<%= link_to 'Edit Video Information', edit_video_path(@video),class:"edit_link" %>
</div>

<script>
$("select").prop("selectedIndex", 0);
$("select").change(function(){
    //alert(($(this)).val());
    console.log(gon.genres);
    if (gon.genres.indexOf( $(this).val()) > -1) {
      $("button").text("Remove Genre")
    } else {
      $("button").text("Add Genre")
    }
});
$("button").click(function(){
  if (gon.movie==true) {
    $.ajax({
      type:"post",
      url:"/manage_genre",
      datatype:"json",
      data: {id:gon.genre_id,genre:$("select").val(),movie:true },
      success:function(data)
      {
        console.log(data);
        if (data["report"]=="add") {
          gon.genres.push($("select").val());
          $("button").text("Remove Genre")
          console.log(gon.genres);
        } else {
          var index= gon.genres.indexOf( $("select").val() );
          gon.genres.splice(index,1);
          $("button").text("Add Genre")
          console.log(gon.genres);
        }
      }
    });
  } else {
    $.ajax({
      type:"post",
      url:"/manage_genre",
      datatype:"json",
      data: {id:gon.genre_id,genre:$("select").val(),movie:false },
      success:function(data)
      {
        console.log(data);
        if (data["report"]=="add") {
          gon.genres.push($("select").val());
          $("button").text("Remove Genre")
          console.log(gon.genres);
        } else {
          var index= gon.genres.indexOf( $("select").val() );
          gon.genres.splice(index,1);
          $("button").text("Add Genre")
          console.log(gon.genres);
        }
      }
    });
  }

});


//**********************************************************************

$(function(){
$('#currentTime').html($('#video_container').find('video').get(0).load());
$('#currentTime').html($('#video_container').find('video').get(0).play());
})
setInterval(function(){
$('#currentTime').html($('#video_container').find('video').get(0).currentTime);
$('#totalTime').html($('#video_container').find('video').get(0).duration);
},500)

document.getElementById('player').addEventListener('loadedmetadata', function() {
  this.currentTime = gon.start;
}, false);


setInterval(function()
{
    $.ajax({
      type:"post",
      url:"/set_time",
      datatype:"json",
      data: {total:$('#video_container').find('video').get(0).duration,time:$('#video_container').find('video').get(0).currentTime,video:gon.id},
      success:function(data)
      {
        console.log(data);
          //do something with response data
      }
    });
}, 30000);//time in milliseconds




var end_popup = setInterval(function()
{
  if ($('#video_container').find('video').get(0).currentTime == $('#video_container').find('video').get(0).duration) {
    if (gon.movie==true) {
      swal("What Next?", {
        buttons: {
          cancel: "Return to video browser",
          catch: {
            text: "Replay",
            value: "catch",
          },
        },
      })
      .then((value) => {
        switch (value) {
          case "catch":
            $('#video_container').find('video').get(0).currentTime=0
            $('#player').get(0).play();
            break;

          default:
            document.location.href = "/movies";
        }
      });
      clearInterval(end_popup)

      //ADD COUNTER
       $(".swal-text").after("<div class='countdown'>Return to movies in <span id='clock'></span></div>");
       var fiveSeconds = new Date().getTime() + 10000;
       $('#clock').countdown(fiveSeconds, function(event) {
         $(this).html(event.strftime('%S Seconds'));
       });
       // AUTO CLICK AFTER 10 SECONDS
      var auto_click = setInterval(function()
      {
          $(".swal-button--cancel").click()
          clearInterval(auto_click)
      }, 10000);//time in milliseconds

    } else {
      swal("What Next?", {
        buttons: {
          cancel: "Return to video browser",
          catch: {
            text: "Replay",
            value: "catch",
          },
          next: "Next Video",
        },
      })
      .then((value) => {
        switch (value) {

          case "next":
            if (gon.next_eps=="end") {
              swal({
                icon: "warning",
                title: "Thats It!",
                text: "No more episodes found :("
              });
            } else {
              document.location.href = gon.next_eps;
            }
            break;

          case "catch":
            $('#video_container').find('video').get(0).currentTime=0
            $('#player').get(0).play();
            break;

          default:
            document.location.href = "/series";
        }
      });
      clearInterval(end_popup)

      //ADD COUNTER
       $(".swal-text").after("<div class='countdown'>Next episode in <span id='clock'></span></div>");
       var fiveSeconds = new Date().getTime() + 10000;
       $('#clock').countdown(fiveSeconds, function(event) {
         $(this).html(event.strftime('%S Seconds'));
       });
       // AUTO CLICK AFTER 10 SECONDS
      var auto_click = setInterval(function()
      {
          $(".swal-button--next").click()
          clearInterval(auto_click)
      }, 10000);//time in milliseconds
    };



  }
}, 1000);//time in milliseconds



</script>