config/routes.rb
Rails.application.routes.draw do
  resources :videos
  resources :series
  resources :genres
  devise_for :users
   resource :contents, :only => :new

      post 'get_videos' => 'series#get_videos'
      post 'get_movie' => 'videos#get_movie'
      post 'set_time' => 'videos#set_time'
      post 'manage_genre' => 'videos#manage_genre'
      get 'movies' => 'videos#movies'
      get 'search' => 'videos#search'

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

   has_many :genres
   has_many :series
   has_many :videos

end

app/controllers/series_controller.rb
class SeriesController < ApplicationController
  before_action :set_series, only: [:show, :edit, :update, :destroy]


  def get_videos
    @series=Series.where("title LIKE ?",params[:title])
    @series=@series.last
    @total_seasons=[]
    @series.videos.each do |v|
      @total_seasons.push(v.season)
    end
    @total_seasons = @total_seasons.uniq
    if params[:season]
      @season=params[:season].to_i
      @videos=@series.videos.where("season LIKE ?",@season)
      @most_recent= @series.videos.order("last_watched").last.title
      respond_to do |format|
        format.json { render :json => {:series => @series, :season => @season, :videos => @videos, :last_watched => @most_recent, :total_seasons => @total_seasons,id:@series.id} }
      end
    else
      if @series.videos.count < 1
        respond_to do |format|
          format.json { render :json => {:id=>@series.id}, :status => 500 }
        end
      else
        @most_recent= @series.videos.order("last_watched").last.title
        @season=@series.videos.order("last_watched").last.season
        @videos=@series.videos.where("season LIKE ?",@season)
        respond_to do |format|
          format.json { render :json => {:series => @series, :season => @season, :videos => @videos, :last_watched => @most_recent, :total_seasons => @total_seasons,id:@series.id} }
        end
      end

    end

  end
  # GET /series
  # GET /series.json
  def index
    @series = Series.all
  end

  # GET /series/1
  # GET /series/1.json
  def show
  end

  # GET /series/new
  def new
    @series = current_user.series.build
  end

  # GET /series/1/edit
  def edit
  end

  # POST /series
  # POST /series.json
  def create
    @series = current_user.series.build(series_params)

    respond_to do |format|
      if @series.save
        format.html { redirect_to "/series", notice: 'Series was successfully created.' }
        format.json { render :show, status: :created, location: @series }
      else
        format.html { render :new }
        format.json { render json: @series.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /series/1
  # PATCH/PUT /series/1.json
  def update
    respond_to do |format|
      if @series.update(series_params)
        format.html { redirect_to @series, notice: 'Series was successfully updated.' }
        format.json { render :show, status: :ok, location: @series }
      else
        format.html { render :edit }
        format.json { render json: @series.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /series/1
  # DELETE /series/1.json
  def destroy
    @series.destroy
    respond_to do |format|
      format.html { redirect_to series_index_url, notice: 'Series was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_series
      @series = Series.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def series_params
      params.require(:series).permit(:title, :desc,genre_ids:[])
    end
end

app/helpers/series_helper.rb
module SeriesHelper
end

app/views/series/_form.html.erb
<div id="devise_wrapper">
<%= form_for(@series) do |f| %>
  <% if @series.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@series.errors.count, "error") %> prohibited this series from being saved:</h2>

      <ul>
      <% @series.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <h2>Search for series </h2>
  <div class="field">
    <label for="basics">Search</label>
    <input id="basics" /><br>
  </div>
  <h2>Or put in your own info </h2>
  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :desc %>
    <%= f.text_area :desc %>
  </div>
  <div class="field check rails_check">
    <%= f.label :genre ,"Add Genre(s)" %><br>
  <%=  f.collection_check_boxes(:genre_ids, current_user.genres.all, :id, :name) do |b| %>
  <%=    b.label(:"data-value" => b.value) { b.check_box + b.text } %><br>
  <%  end %><br>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
</div>
<%if false%>
  <% f.collection_check_boxes(:genre_ids, current_user.genres.all, :id, :name) %>
<%end%>
<script>
var counter = 0

//var options = {
//	data: [""]
//};
//$("#basics").easyAutocomplete(options);

list=""
var search_results=[]
var id_results=[]
var ids=''

$("#basics").keypress(function(){
  $('#basics').focus();
//  var options = {
  // data: search_results
  //};
  //$("#basics").easyAutocomplete(options);
  //$('#basics').focus();

  $.getJSON("https://api.themoviedb.org/3/search/tv?api_key=5041b86cde2ce6de2f60c84e6fccd66c&query="+$("#basics").val(),function(data){
     results= data.results
     list=''
     ids=''
      for(i=0;i<5;i++){
        list=list+data.results[i]["original_name"]+","
        ids=ids+data.results[i]["id"]+","
        counter+=1
      }
    search_results=list.split(",")
    id_results=ids.split(",")
    $('#basics').focus();
  });
  if (counter > 0) {
    $(".search_poster").remove();
    for(i=0;i<5;i++){
      $.getJSON("https://api.themoviedb.org/3/tv/"+parseInt(id_results[i])+"?api_key=5041b86cde2ce6de2f60c84e6fccd66c&language=en-US",function(data){
         results= data.results
         $("#new_series_wrapper").append("<img class='search_poster "+data["name"]+"'src='http://image.tmdb.org/t/p/w780/"+data["poster_path"] + "' alt='"+data["name"]+"'>");
         $(".search_poster").click(function(){
           $.getJSON("https://api.themoviedb.org/3/search/tv?api_key=5041b86cde2ce6de2f60c84e6fccd66c&query="+$("#series_title").val(),function(data){
                 id=data.results[0]["id"]
                 console.log(id);
                   $.getJSON("https://api.themoviedb.org/3/tv/"+id+"?api_key=5041b86cde2ce6de2f60c84e6fccd66c&language=en-US",function(data){
                       desc=data["overview"]
                       $('#series_desc').val(desc);
                 });
           });
             $('#series_title').val($(this).attr("class").substring(14));
         });
      });
    }

    counter=0
  }
});



</script>

app/views/series/edit.html.erb
<h1>Editing Series</h1>

<%= render 'form' %>

<%= link_to 'Delete Series', @series, method: :delete, data: { confirm: 'Are you sure?' },class: 'delete_link' %>

app/views/series/index.html.erb
<div id='series_wrapper'>
  <h1>All Series</h1>
  <h2><%= link_to 'Add Too Exsiting Series', new_video_path,:class => 'video_link' %> | <%= link_to 'Add New Series', new_series_path %></h2>
  <%@counter=1%>
  <% @series.each do |series| %>
    <%@search = Tmdb::Search.new %>
    <%@search.resource('tv') %>
    <%@search.query(series.title) %>
    <% if @search.fetch[0] != nil%>
      <%@tv_series_id=@search.fetch[0]["id"] %>
      <%@pics = Tmdb::TV.images(@tv_series_id) %>
      <% if @pics['backdrops'][1]  != nil%>
        <% @pics['backdrops'][1]["file_path"] %>
        <%= image_tag("http://image.tmdb.org/t/p/w780/#{@pics['backdrops'][1]["file_path"]}", :class => "#{series.title}", :id=>@counter)%>
      <%else%>
        <%= image_tag("/tv_placeholder.jpg", :class => "#{series.title}", :id=>@counter)%>
      <%end%>
    <%else%>
    <%= image_tag("/tv_placeholder.jpg", :class => "#{series.title}", :id=>@counter)%>
    <%end%>
    <%@counter+=1%>
  <% end %>

</div>
<h1>Thats all your series!</h1>
<h2 style="text-align:center;"><%= link_to 'Add More', new_series_path,:class => 'video_link' %></h2>



<script>
function hasClass(elem, className) {
    return elem.className.split(' ').indexOf(className) > -1;
}



$("img").click(function(){
  console.log($(this).next().length);
  $("#dropdown").remove();
  if ($(this).attr("id")%2 == 0) {
    $(this).after("<div id='dropdown'><h1>"+$(this).attr('class')+"</h1></div>");
  } else if ( $(this).next().length == 0) {
    $(this).after("<div id='dropdown'><h1>"+$(this).attr('class')+"</h1></div>");
  } else {
    $(this).next().after("<div id='dropdown'><h1>"+$(this).attr('class')+"</h1></div>");
  }

  var classs=$(this).attr('class')
  $.ajax({
    type: "POST",
    url: "/get_videos",
    dataType:"json",
    data: {"title":$(this).attr('class')},
    success:function(data) {
      var total_seasons=data["total_seasons"];
      var season=data["season"];
      var series=data["series"]
      var videos=data["videos"]
      var amount=videos.length
      if (data["series"]["desc"].length>300) {
        var series_desc= data["series"]["desc"].substring(0, 500)+"...";
      } else {
        var series_desc= data["series"]["desc"];
      };
      $( " <a href='/series/"+data["id"]+"/edit'>Edit</a> " ).appendTo( "#dropdown" );
      $( "<h2>"+series_desc+"</h2>" ).appendTo( "#dropdown" );
      $("<h4>"+amount+" episodes<br>Season: </h4>").appendTo( "#dropdown" );
      var s = $("<select id='season_select' class='"+classs+" seaon_select' />");
      s.appendTo('#dropdown');


      $( "<div class='owl-carousel'></div>" ).appendTo( "#dropdown" );
      for(i=0;i<amount;i++){
        if (videos[i]["desc"].length>300) {
          var desc= videos[i]["desc"].substring(0, 300)+"...";
        } else {
          var desc= videos[i]["desc"];
        };
        if (videos[i]["total_time"] != null) {
          var remaining=(videos[i]["left_off"]/videos[i]["total_time"])*100
        } else {
          var remaining=0
        }
        // VIDEO DIV
        $("<div class='video_divs'><a href='/videos/"+videos[i]["id"]+"'> <img src="+videos[i]["poster"]+
        "  /> </a> <p class='video_title'>"+videos[i]["title"]+
        "</p><p><div class='meter'><span style='width: "+remaining+"%'></span></div></p>  <p class='video_desc'>"+desc+"</h3></div>").appendTo( ".owl-carousel" );


      }
      $(".owl-carousel").owlCarousel({
        items : 5,
        margin: 20,
        responsiveClass:true,
        responsive:{
            0:{
                items:1
            },
            600:{
                items:3
            },
            1000:{
                items:5
            }
        }
      });
      $("p:contains("+data["last_watched"]+")").parent().css({"color":"black","background-color":"#F2E980"})
      for(var val in total_seasons) {
          $('<option />', {value: total_seasons[val], text: total_seasons[val]}).appendTo(s);
      }
      $("#season_select").val(season);
    },
    error:function(data) {
      $( " <a href='/series/"+data['responseJSON']['id']+"/edit'>Edit</a> " ).appendTo( "#dropdown" );
      $( "<h2>No Episodes Added Yet <br>  <a href='/videos/new'>Add Some Now!</a> </h2>" ).appendTo( "#dropdown" );
      return false;
    }
  });
});

document.addEventListener('change', function (e) {
    if (hasClass(e.target, 'seaon_select')) {
              var name = $('#season_select').attr('class').slice(0, -13)
              var season_number=$( "#season_select option:selected" ).text()
            //alert($(this).val());
            // RESENDS AJAX REQUEST WHEN CHANGING SEASON NUMBER*****************************
              $(".owl-carousel").remove();
              $('h2').remove();
              $('h4').remove();
              $('#season_select').remove();
              $( "#dropdown a" ).remove();
              var classs=name;
              $.ajax({
                type: "POST",
                url: "/get_videos",
                dataType:"json",
                data: {"title":name,"season":season_number},
                success:function(data) {
                  var total_seasons=data["total_seasons"];
                  var season=data["season"];
                  var series=data["series"];
                  var videos=data["videos"];
                  var amount=videos.length;
                  $( " <a href='/series/"+data["id"]+"/edit'>Edit</a> " ).appendTo( "#dropdown" );
                  $( "<h2>"+data["series"]["desc"]+"</h2>" ).appendTo( "#dropdown" );
                  $("<h4>"+amount+" episodes<br>Season: </h4>").appendTo( "#dropdown" );
                  var s = $("<select id='season_select' class='"+classs+" seaon_select' />");
                  s.appendTo('#dropdown');
                  $( "<div class='owl-carousel'></div>" ).appendTo( "#dropdown" );
                  for(i=0;i<amount;i++){
                    if (videos[i]["desc"].length>300) {
                      var desc= videos[i]["desc"].substring(0, 300)+"...";
                    } else {
                      var desc= videos[i]["desc"];
                    };
                    if (videos[i]["total_time"] != null) {
                      var remaining=(videos[i]["left_off"]/videos[i]["total_time"])*100
                    } else {
                      var remaining=0
                    }
                    // VIDEO DIV
                    $("<div class='video_divs'><a href='/videos/"+videos[i]["id"]+"'> <img src="+videos[i]["poster"]+
                    "  /> </a> <p class='video_title'>"+videos[i]["title"]+
                    "</p><p><div class='meter'><span style='width: "+remaining+"%'></span></div></p>  <p class='video_desc'>"+desc+"</h3></div>").appendTo( ".owl-carousel" );

                  }
                  $(".owl-carousel").owlCarousel({
                    items : 5,
                    margin: 20,
                    responsiveClass:true,
                    responsive:{
                        0:{
                            items:1
                        },
                        600:{
                            items:3
                        },
                        1000:{
                            items:5
                        }
                    }
                  });
                  $("p:contains("+data["last_watched"]+")").parent().css({"color":"black","background-color":"#F2E980"})
                  for(var val in total_seasons) {
                      $('<option />', {value: total_seasons[val], text: total_seasons[val]}).appendTo(s);
                  }
                  $("#season_select").val(season);
                },
                error:function(data) {
                  $( " <a href='/series/"+data['responseJSON']['id']+"/edit'>Edit</a> " ).appendTo( "#dropdown" );
                  $( "<h2>No Episodes Added Yet <br>  <a href='/videos/new'>Add Some Now!</a> </h2>" ).appendTo( "#dropdown" );
                  return false;
                }
              });
    }
}, false);

</script>

app/views/series/new.html.erb
<div id='new_series_wrapper'>
  <h1>New Series</h1>
  <p class='edit_p'>(If search not working type slowly the title from the start, its a bit finicky)</p>
  <%= render 'form' %>
</div>

app/views/series/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @series.title %>
</p>

<p>
  <strong>Desc:</strong>
  <%= @series.desc %>
</p>


<% @series.videos.each do |video| %>

  <div class="video_preview">
    <%= link_to (video) do %>
      <img src= <%=video.poster%> /><br>
    <%end%>
    <%=video.title%><br>
    <%=video.desc%>
  </div>

<% end %>
<%= link_to 'Edit', edit_series_path(@series) %> |
<%= link_to 'Back', series_index_path %>